baseURL = 'http://ventdrop.github.io/'
languageCode = 'en-us'
title = 'Vent Drop | an infosec blog'
theme = "geocities-reaper"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "writeups"
    name = "WriteUps"
    url = "/tags/writeups/"
    weight = 4

[params]
  author = "RG"
  avatar = "/avatar.jpg"
  menu_item_separator = " - "
  subtitle = "bfake"
  description = "^^"
  location = "Cyberspace"
  mood = "pensive"
  welcome_message = "images/hackerman.webp"
  quote = "... That no single, individual moment is in and of itself unendurable."
  quote_author = "David Foster Wallace, Infinite Jest"
  about = "cybersecurity professional, orioles/ravens fan, musician, novelty claw machine enjoyer"
  guestbook = false
  links = true
  
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/ventdrop"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/ventdrop"